### ISSUE TITLE
Warning: <stdin>: syntax error in line 1 near 'No'

### ISSUE THREAD

**Issue by galindro** [nickjj/ansigenome#21] opened 2015-05-12 13:06 UTC
If I use the command line to export roles dependencies into a png file, the bellow error is displayed:

```bash
$ ansigenome export ./git_repos/devops/roles/ -o ./git_repos/devops/roles/role_schema.png
Warning: <stdin>: syntax error in line 1 near 'No'
```

But it works if I go to role directory and execute the command like as bellow:

```bash
$ cd ./git_repos/devops/roles/ && ansigenome export -o role_schema.png
```

**Comment by conorsch** [comment] 2015-05-12 15:47
The issue you describe has plagued me for a while, too:

```
$ ansigenome export roles -o role_schema.png
Warning: <stdin>: syntax error in line 1 near 'No'
```
Even running the command from within my roles directory doesn't help:

```
$ cd roles && ansigenome export -o role_schema.png
Warning: <stdin>: syntax error in line 20 near '-'
```

Interesting that we're getting different syntax errors. I assume this is related to YAML parsing, but the error message is rather ambiguous. This error occurs on v0.5.3.

**Comment by nickjj** [comment] 2015-05-12 16:52
@conorsch Do the other anisigenome commands run without issues?

**Comment by conorsch** [comment] 2015-05-12 19:30
@nickjj Yes, every ansigenome command except `export` runs without error. Previously I'd only tried `ansigenome scan <roles_dir>`,  since the other commands seem tailored to roles distributed via galaxy. Just now I tested each one and encountered no issues.

**Comment by focusaurus** [comment] 2015-06-16 23:50
I'm getting a similar error. My hunch is ansigenome is passing a mix of valid instructions and a plain-text error message like "No such file or directory" or some variation of that into the graphviz stdin, based on my error message and @conorsch's. Here's mine:

```
ansigenome export -o /tmp/deps.png -f png
Error: <stdin>: syntax error in line 23 near '.'
```

**Comment by boneill42** [comment] 2015-11-12 15:46
+1, i ran into the same thing.

**Comment by ypid** [comment] 2015-11-12 18:13
@focusaurus The dot issue should be fixed by #36. Can anyone provide the dot file to analyses this issue further? `ansigenome export -o role_schema.dot -f dot`

**Comment by nickjj** [comment] 2015-11-13 02:05
Thanks @ypid, I just merged it.

Expect a new version of Ansigenome in a day or 2 on PyPi.

**Comment by nickjj** [comment] 2015-12-01 13:54
@conorsch Someone else just reported your same issue. We started eliminating roles until it worked.

The issue is one or more of your roles may have hyphens in them, and the error is thrown when you reference those roles as dependencies in `meta/main.yml`.

For example:

This fails: `- { role: foobar-hello }`
This fails: `- { role: 'foobar-hello' }`
This works: `- { role: foobar.hello }`

Can you validate the above on your end?

**Comment by nickjj** [comment] 2015-12-01 15:33
Closing this as the new `v0.5.6` version fixes this along with a number of other issues. It's up on PyPi.

**Closed by nickjj** 2015-12-01 15:33 UTC

**Comment by conorsch** [comment] 2015-12-01 17:29
@nickjj Great! Still waiting on `v0.5.6` to hit `pip`, then I'll grab the new version and confirm the fix.

**Comment by nickjj** [comment] 2015-12-01 17:33
Oh wow, I published it to PyPi test instead of live. It should be good now.

https://pypi.python.org/pypi/ansigenome/0.5.6
